services:
  ddos-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx-logs:/var/log/nginx
    command: /bin/sh -c "rm -f /var/log/nginx/access.log /var/log/nginx/error.log && nginx -g 'daemon off;'"

  ddos-redis:
    image: redis:alpine
    container_name: ddos-redis
    ports:
      - "6379:6379"

  ml-detector:
    build: .
    container_name: ddos-ml-engine
    volumes:
      - nginx-logs:/var/log/nginx
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ddos-redis

volumes:
  nginx-logs:
