events { worker_connections 1024; }

http {
    log_format json_analytics escape=json '{'
        '"time":"$time_iso8601",'
        '"remote_addr":"$remote_addr",'
        '"request_uri":"$request_uri",'
        '"status": "$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"http_user_agent":"$http_user_agent"'
    '}';

    access_log /var/log/nginx/access.json json_analytics;

    limit_req_zone $binary_remote_addr zone=ip_limit:10m rate=10r/s;

    server {
        listen 80;

        location / {
            limit_req zone=ip_limit burst=5 nodelay;

            access_by_lua_block {
                local redis = require "resty.redis"
                local red = redis:new()
                red:set_timeout(1000)

                local ok, err = red:connect("redis", 6379)
                if not ok then
                    ngx.log(ngx.ERR, "Redis connection failed: ", err)
                    return 
                end

                local client_ip = ngx.var.remote_addr
                local is_banned, err = red:get("ban:" .. client_ip)

                if is_banned == "1" then
                    ngx.log(ngx.WARN, "BANNED IP DENIED: ", client_ip)
                    ngx.exit(ngx.HTTP_FORBIDDEN)
                end
            }

            default_type text/html;
            return 200 "<html><body><h1>Passed Shield: Request Successful!</h1></body></html>";
        }
    }
}
